version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/zannen/timeseries
    steps:
      - checkout
      - run: make deps
      - run: make test
      - run: make codecov_io
